Repository jupyter-server/jupyter-scheduler, pull requests merged in 2022-11, with the labels that each got.

#239 fix pagination in AdvancedTable
  src/components/advanced-table/advanced-table.tsx
Labels: bug

#241 Chooses the first environment in the create form
  src/mainviews/create-job.tsx
Labels: bug

#230 Add additional styling of backgound and paper to handle dark mode.
  src/theme-provider.ts
Labels: bug

#244 Added release workflows
  .github/workflows/check-release.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  package.json
Labels: maintenance

#227 Create job from job definition - UI
  src/handler.ts
  src/mainviews/create-job-from-definition.tsx
  src/mainviews/create-job.tsx
  src/mainviews/detail-view/job-definition.tsx
  src/model.ts
  src/notebook-jobs-panel.tsx
Labels: enhancement

#246 Hides Output Format picker when no output formats are present
  src/components/output-format-picker.tsx
Labels: bug

#248 Increase download delay from 500 ms to 5 s
  src/components/job-row.tsx
  src/mainviews/detail-view/job-detail.tsx
Labels: enhancement

#250 Fix for failing check-release workflow
  package.json
Labels: maintenance

#238 make job definitions editable
  src/components/create-schedule-options.tsx
  src/components/schedule-inputs.tsx
  src/handler.ts
  src/mainviews/create-job.tsx
  src/mainviews/detail-view/detail-view.tsx
  src/mainviews/detail-view/job-definition.tsx
  src/mainviews/edit-job-definition.tsx
  src/model.ts
  src/notebook-jobs-panel.tsx
  style/labeled-value.css
Labels: enhancement

#245 Confirmation for stop with visual feedback on request for Job List, Job Detail
  src/components/confirm-buttons.tsx
  src/components/confirm-delete-button.tsx
  src/components/confirm-delete-icon.tsx
  src/components/confirm-dialog-buttons.tsx
  src/components/job-definition-row.tsx
  src/components/job-row.tsx
  src/mainviews/detail-view/job-definition.tsx
  src/mainviews/detail-view/job-detail.tsx
Labels: enhancement

#249 render better empty list messages
  src/mainviews/detail-view/job-definition.tsx
  src/mainviews/list-jobs.tsx
Labels: enhancement

#247 allow arbitrary expressions as job parameters
  jupyter_scheduler/models.py
  jupyter_scheduler/parameterize.py
  src/handler.ts
Labels: enhancement

#258 Making name as required in models
  jupyter_scheduler/models.py
  jupyter_scheduler/tests/test_handlers.py
  jupyter_scheduler/tests/test_job_files_manager.py
  src/handler.ts
  src/model.ts
Labels: enhancement

#261 fix schedule validation errors not clearing after selecting run now
  src/components/create-schedule-options.tsx
  src/model.ts
Labels: bug

#253 Catching create job failures, updates to job definition
  jupyter_scheduler/task_runner.py
Labels: bug

#264 refactor schedule inputs
  src/components/create-schedule-options.tsx
  src/components/schedule-inputs.tsx
  src/model.ts
  src/notebook-jobs-panel.tsx
Labels: bug, enhancement

#266 move input job file link
  src/components/job-file-link.tsx
  src/components/job-row.tsx
  src/components/labeled-value.tsx
  src/mainviews/detail-view/job-detail.tsx
  src/mainviews/list-jobs.tsx
  src/model.ts
Labels: enhancement

#265 Adds UTC-only option to environment model
  jupyter_scheduler/models.py
  src/components/create-schedule-options.tsx
  src/components/schedule-inputs.tsx
  src/handler.ts
  src/mainviews/create-job.tsx
Labels: enhancement

#270 Enabled outputs for failed jobs
  jupyter_scheduler/executors.py
  jupyter_scheduler/job_files_manager.py
  src/components/job-row.tsx
  src/mainviews/detail-view/job-detail.tsx
Labels: enhancement

#273 Allows spaces in job names, except in the first position
  src/util/job-name-validation.tsx
Labels: enhancement

#277 Adds error reporting
  src/components/error-boundary.tsx
  src/notebook-jobs-panel.tsx
  style/base.css
Labels: bug, enhancement

#278 Bump jupyter-server version ceiling
  pyproject.toml
Labels: enhancement

#280 hide timezone selector when editing job definition created with utc_only environment
  dev/seed.py
  src/mainviews/edit-job-definition.tsx
  src/model.ts
  src/notebook-jobs-panel.tsx
Labels: bug

#283 Uses same schema for create job/JD error
  src/mainviews/create-job.tsx
Labels: bug

#284 Error alerts in list job definitions view
  src/components/job-definition-row.tsx
  src/handler.ts
  src/mainviews/list-jobs.tsx
Labels: enhancement

#287 Adds tooltips to job definition links from list view
  src/components/job-definition-row.tsx
Labels: bug

#286 Errors for pause, resume, delete in detail page and list view
  src/components/job-definition-row.tsx
  src/mainviews/detail-view/job-definition.tsx
  src/mainviews/detail-view/job-detail.tsx
  src/mainviews/list-jobs.tsx
Labels: enhancement

#288 Adds error wrapper for list queries
  src/components/advanced-table/advanced-table.tsx
Labels: enhancement

#294 suppress warning raised by jupyter-core
  .github/workflows/build.yml
Labels: bug

#292 correctly handle last page even when latest next_token is truthy
  src/components/advanced-table/advanced-table.tsx
Labels: bug

#299 Fixed propagation of error message to UI
  src/handler.ts
Labels: bug

#297 Display success message on list view after creating a job
  src/components/job-row.tsx
  src/mainviews/create-job.tsx
  src/mainviews/list-jobs.tsx
  src/notebook-jobs-panel.tsx
Labels: enhancement

#301 Adds success message on "run job from definition"
  src/mainviews/create-job-from-definition.tsx
  src/mainviews/detail-view/job-definition.tsx
Labels: bug

#302 Added exception handling to both api handlers and UI
  CHANGELOG.md
  jupyter_scheduler/handlers.py
  jupyter_scheduler/scheduler.py
  src/handler.ts
  src/mainviews/detail-view/detail-view.tsx
Labels: bug, enhancement

#307 Updates "Download job files" tooltip in list jobs view
  src/components/job-row.tsx
Labels: bug

#308 Displays errors on edit job definition page
  src/mainviews/edit-job-definition.tsx
Labels: enhancement

#312 Add readme links
  README.md
  docs/contributors/index.md
Labels: documentation

#314 Adds override for job files manager, more error handlers
  docs/operators/index.md
  jupyter_scheduler/extension.py
  jupyter_scheduler/job_files_manager.py
  src/components/job-row.tsx
  src/handler.ts
  src/mainviews/detail-view/job-detail.tsx
  src/mainviews/list-jobs.tsx
Labels: enhancement

#315 Adds reload on detail page
  src/components/button-bar.tsx
  src/mainviews/detail-view/detail-view.tsx
  src/mainviews/detail-view/job-definition.tsx
  src/mainviews/detail-view/job-detail.tsx
Labels: enhancement

#285 Update file snapshot in job definitions
  jupyter_scheduler/models.py
  jupyter_scheduler/scheduler.py
  src/components/input-file-snapshot.tsx
  src/handler.ts
  src/mainviews/edit-job-definition.tsx
  src/model.ts
  src/notebook-jobs-panel.tsx
  style/base.css
  style/edit-job-definitions.css
Labels: enhancement

#309 Added exception handlers, simplified imports
  jupyter_scheduler/handlers.py
  jupyter_scheduler/models.py
  jupyter_scheduler/tests/test_handlers.py
Labels: bug
