Repository jupyter-server/jupyter-scheduler, pull requests merged in 2022-09, with the labels that each got.

#9 Automated Changelog Entry for 0.1.0 on main
  CHANGELOG.md
Labels: documentation

#12 CollapsiblePanel
  src/components/collapsible-panel.tsx
  style/base.css
  style/collapsible-panel.css
Labels: enhancement

#43 Fix params picker when zero params exist
  src/components/parameters-picker.tsx
  src/mainviews/create-job.tsx
Labels: bug

#49 Automated Changelog Entry for 0.2.1 on main
  CHANGELOG.md
Labels: documentation

#56 Adds idempotency token and tags for use in create job, details view
  src/advanced-options.tsx
  src/mainviews/create-job.tsx
  src/mainviews/job-detail.tsx
  src/model.ts
  src/notebook-jobs-panel.tsx
Labels: enhancement
