Repository jupyter-server/jupyter-scheduler, pull requests merged in 2022-10, with the labels that each got.

#71 Fix for deduping token for advanced options extension point
  src/advanced-options.tsx
  src/components/parameters-picker.tsx
  src/index.tsx
  src/mainviews/create-job.tsx
  src/mainviews/job-detail.tsx
  src/notebook-jobs-panel.tsx
  src/tokens.ts
Labels: bug

#74 Added default formats when no formats are selected
  jupyter_scheduler/scheduler.py
Labels: bug

#60 Job Detail refactor
  src/advanced-options.tsx
  src/mainviews/job-detail.tsx
  src/model.ts
Labels: enhancement

#137 Fixes error when job definition is deleted.
  jupyter_scheduler/task_runner.py
Labels: bug

#146 Output files manager, user triggered download of output files
  CHANGELOG.md
  conftest.py
  jupyter_scheduler/config.py
  jupyter_scheduler/environments.py
  jupyter_scheduler/executors.py
  jupyter_scheduler/extension.py
  jupyter_scheduler/handlers.py
  jupyter_scheduler/models.py
  jupyter_scheduler/orm.py
  jupyter_scheduler/output_files_manager.py
  jupyter_scheduler/scheduler.py
  jupyter_scheduler/task_runner.py
  jupyter_scheduler/tests/mocks.py
  jupyter_scheduler/tests/test_handlers.py
  jupyter_scheduler/tests/test_scheduler.py
  jupyter_scheduler/utils.py
  pyproject.toml
  src/components/job-row.tsx
  src/handler.ts
  src/index.tsx
  src/mainviews/detail-view/detail-view.tsx
  src/mainviews/detail-view/job-detail.tsx
  src/mainviews/list-jobs.tsx
  src/model.ts
Labels: enhancement

#167 Fix for create job UI when error is returned from backend
  src/mainviews/create-job.tsx
Labels: bug

#168 Update release doc
  .github/workflows/check-release.yml
  .github/workflows/enforce-label.yml
  RELEASE.md
Labels: maintenance

#143 Adds helper text to Output path in create form
  src/handler.ts
  src/index.tsx
  src/mainviews/create-job.tsx
  src/mainviews/detail-view/job-definition.tsx
  src/mainviews/detail-view/job-detail.tsx
Labels: enhancement

#181 Sets initial crontab for schedule
  src/advanced-options.tsx
  src/components/job-row.tsx
  src/mainviews/detail-view/job-detail.tsx
  src/model.ts
Labels: enhancement

#183 Limits maximum size of compute type dropdown
  src/components/compute-type-picker.tsx
  src/mainviews/create-job.tsx
Labels: enhancement

#185 Removes status bar widget
  src/components/running-jobs-indicator.tsx
  src/index.tsx
Labels: enhancement

#187 When one environment is present, selects first compute type; propagates compute type on rerun
  src/components/job-row.tsx
  src/mainviews/create-job.tsx
  src/mainviews/detail-view/job-detail.tsx
Labels: bug

#171 Async support, configurable staging path, tar file support
  jupyter_scheduler/executors.py
  jupyter_scheduler/handlers.py
  jupyter_scheduler/output_files_manager.py
  jupyter_scheduler/scheduler.py
  pyproject.toml
Labels: bug, enhancement

#193 Removes environment picker from UI when exactly one environment is present
  src/components/environment-picker.tsx
Labels: enhancement

#186 Disable create on submit
  src/mainviews/create-job.tsx
  src/model.ts
Labels: enhancement

#189 Added jobs directory to store input copy and outputs
  jupyter_scheduler/executors.py
  jupyter_scheduler/extension.py
  jupyter_scheduler/handlers.py
  jupyter_scheduler/job_files_manager.py
  jupyter_scheduler/models.py
  jupyter_scheduler/orm.py
  jupyter_scheduler/scheduler.py
  jupyter_scheduler/task_runner.py
  jupyter_scheduler/tests/test_handlers.py
  jupyter_scheduler/tests/test_job_files_manager.py
  jupyter_scheduler/tests/test_scheduler.py
  jupyter_scheduler/tests/test_staging_dir/job-1/helloworld-1.html
  jupyter_scheduler/tests/test_staging_dir/job-1/helloworld-1.ipynb
  jupyter_scheduler/tests/test_staging_dir/job-1/helloworld.ipynb
  jupyter_scheduler/tests/test_staging_dir/job-2/helloworld.tar.gz
  jupyter_scheduler/utils.py
  src/components/job-definition-row.tsx
  src/components/job-row.tsx
  src/handler.ts
  src/index.tsx
  src/mainviews/create-job.tsx
  src/mainviews/detail-view/job-detail.tsx
  src/mainviews/list-jobs.tsx
  src/model.ts
Labels: enhancement

#197 Adds default compute type to runtime env model, uses it
  jupyter_scheduler/models.py
  src/handler.ts
  src/mainviews/create-job.tsx
Labels: enhancement

#198 Select all output formats by default
  src/components/output-format-picker.tsx
  src/mainviews/create-job.tsx
Labels: enhancement

#203 Allow user to create a job with no output formats
  jupyter_scheduler/scheduler.py
Labels: enhancement

#202 Support backends without `total_count` in list views
  .gitignore
  dev/seed.py
  dev/templates/1.ipynb
  dev/templates/2.ipynb
  dev/templates/3.ipynb
  src/components/advanced-table/advanced-table.tsx
  src/handler.ts
  src/mainviews/detail-view/job-detail.tsx
Labels: bug, enhancement

#207 merge `ListJobsView` into `JobsView`, re-define `IAdvancedOptionsProps`
  src/advanced-options.tsx
  src/components/advanced-table/advanced-table.tsx
  src/index.tsx
  src/mainviews/create-job.tsx
  src/mainviews/detail-view/detail-view.tsx
  src/mainviews/detail-view/job-definition.tsx
  src/mainviews/detail-view/job-detail.tsx
  src/mainviews/list-jobs.tsx
  src/model.ts
  src/notebook-jobs-panel.tsx
  src/tokens.ts
Labels: enhancement

#212 fix view for empty list
  src/components/advanced-table/advanced-table.tsx
Labels: bug

#206 Creates directory based on job name, not based on timestamp
  jupyter_scheduler/orm.py
  jupyter_scheduler/scheduler.py
  jupyter_scheduler/utils.py
Labels: bug

#221 Add maxWidth, use LabeledValue in Detail View (#2)
  src/components/labeled-value.tsx
  src/mainviews/detail-view/detail-view.tsx
  src/mainviews/detail-view/job-definition.tsx
  src/mainviews/detail-view/job-detail.tsx
  style/base.css
  style/labeled-value.css
Labels: enhancement

#218 Blocks job or job definition creation when a parameter has no key and no value
  src/components/parameters-picker.tsx
Labels: bug

#219 Generic api errors, delete staging files on job delete
  jupyter_scheduler/exceptions.py
  jupyter_scheduler/handlers.py
  jupyter_scheduler/scheduler.py
Labels: enhancement

#226 Use LabeledValue in advanced options in Job Definition and Job Definition Detail
  src/advanced-options.tsx
  src/components/labeled-value.tsx
Labels: bug
