Repository jupyter-server/jupyter-scheduler, pull requests merged in 2023-08, with the labels that each got.

#417 Fix CI, run lint, reduce end-to-end tests flakiness
  .github/workflows/build.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/update-integration-tests.yml
  ui-tests/helpers/SchedulerHelper.ts
  ui-tests/tests/jupyter_scheduler.spec.ts
  ui-tests/tests/jupyter_scheduler.spec.ts-snapshots/list-view-linux.png
  ui-tests/tests/jupyter_scheduler.spec.ts-snapshots/notebook-toolbar-linux.png
  ui-tests/tests/jupyter_scheduler.spec.ts-snapshots/notebook-view-linux.png
Labels: bug, maintenance, Testing

#388 Archiving all-files scheduler
  docs/operators/index.md
  jupyter_scheduler/executors.py
  jupyter_scheduler/job_files_manager.py
  jupyter_scheduler/scheduler.py
Labels: enhancement

#424 Fix JFM tests
  jupyter_scheduler/job_files_manager.py
  jupyter_scheduler/tests/test_job_files_manager.py
Labels: bug

#419 Avoids "filter" option in tarfile
  jupyter_scheduler/job_files_manager.py
Labels: bug

#425 [1.x] Fix CI, run lint, reduce end-to-end tests flakiness
  .github/workflows/build.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/update-integration-tests.yml
  .gitignore
  ui-tests/helpers/SchedulerHelper.ts
  ui-tests/tests/jupyter_scheduler.spec.ts
  ui-tests/tests/jupyter_scheduler.spec.ts-snapshots/create-view-empty-linux.png
  ui-tests/tests/jupyter_scheduler.spec.ts-snapshots/create-view-from-filebrowser-linux.png
  ui-tests/tests/jupyter_scheduler.spec.ts-snapshots/create-view-from-toolbar-linux.png
  ui-tests/tests/jupyter_scheduler.spec.ts-snapshots/filebrowser-menu-linux.png
  ui-tests/tests/jupyter_scheduler.spec.ts-snapshots/filebrowser-notebook-rightclick-menu-linux.png
  ui-tests/tests/jupyter_scheduler.spec.ts-snapshots/launcher-linux.png
  ui-tests/tests/jupyter_scheduler.spec.ts-snapshots/launcher-with-scheduler-linux.png
  ui-tests/tests/jupyter_scheduler.spec.ts-snapshots/list-view-in-progress-linux.png
  ui-tests/tests/jupyter_scheduler.spec.ts-snapshots/list-view-linux.png
  ui-tests/tests/jupyter_scheduler.spec.ts-snapshots/notebook-toolbar-linux.png
  ui-tests/tests/jupyter_scheduler.spec.ts-snapshots/notebook-with-createjob-button-linux.png
Labels: enhancement

#418 [1.x] Archiving scheduler, fix JFM tests
  docs/operators/index.md
  jupyter_scheduler/executors.py
  jupyter_scheduler/job_files_manager.py
  jupyter_scheduler/scheduler.py
  jupyter_scheduler/tests/test_job_files_manager.py
Labels: enhancement

#422 Add version specifiers for all dependencies
  pyproject.toml
Labels: enhancement

#427 [1.x] Add version specifiers for all dependencies
  pyproject.toml
Labels: enhancement
