Repository jupyter-server/jupyter-scheduler, pull requests merged in 2023-07, with the labels that each got.

#391 Pins Pydantic to version 1, adds Python 3.11
  pyproject.toml
Labels: bug

#387 Add UI tests
  .github/workflows/binder-on-pr.yml
  .github/workflows/update-integration-tests.yml
  docs/contributors/index.md
  pyproject.toml
  ui-tests/helpers/SchedulerHelper.ts
  ui-tests/tests/jupyter_scheduler.spec.ts
  ui-tests/tests/jupyter_scheduler.spec.ts-snapshots/create-view-empty-linux.png
  ui-tests/tests/jupyter_scheduler.spec.ts-snapshots/create-view-from-toolbar-linux.png
  ui-tests/tests/jupyter_scheduler.spec.ts-snapshots/filebrowser-notebook-rightclick-menu-linux.png
  ui-tests/tests/jupyter_scheduler.spec.ts-snapshots/launcher-with-scheduler-linux.png
  ui-tests/tests/jupyter_scheduler.spec.ts-snapshots/list-view-in-progress-linux.png
  ui-tests/tests/jupyter_scheduler.spec.ts-snapshots/notebook-with-createjob-button-linux.png
  ui-tests/yarn.lock
Labels: enhancement, maintenance, Testing

#404 allow update E2E snapshots job to be manually triggered
  .github/workflows/update-integration-tests.yml
Labels: enhancement
