Repository jupyter-server/jupyter-scheduler, pull requests merged in 2023-10, with the labels that each got.

#438 Fix RTD and E2E CI workflows
  .github/workflows/e2e-tests.yml
  .readthedocs.yml
  ui-tests/package.json
  ui-tests/yarn.lock
Labels: maintenance

#444 [1.x] Fix RTD CI workflow
  .github/workflows/e2e-tests.yml
  .readthedocs.yml
Labels: maintenance

#437 Remove unused s3fs dependency
  pyproject.toml
Labels: maintenance, dependencies

#443 [1.x] Remove unused s3fs dependency
  pyproject.toml
Labels: maintenance, dependencies

#448 Added telemetry support.
  .gitignore
  src/components/create-schedule-options.tsx
  src/components/job-definition-row.tsx
  src/components/job-file-link.tsx
  src/components/job-row.tsx
  src/context.ts
  src/hooks.ts
  src/index.tsx
  src/mainviews/create-job-from-definition.tsx
  src/mainviews/create-job.tsx
  src/mainviews/detail-view/job-definition.tsx
  src/mainviews/detail-view/job-detail.tsx
  src/mainviews/edit-job-definition.tsx
  src/mainviews/list-jobs.tsx
  src/notebook-jobs-panel.tsx
  src/tokens.ts
Labels: enhancement

#452 Migrate from hub to gh in workflows
  .github/workflows/update-integration-tests.yml
Labels: bug

#450 Fix "event loop is already running" bug on Linux
  jupyter_scheduler/scheduler.py
  ui-tests/tests/jupyter_scheduler.spec.ts-snapshots/list-view-linux.png
Labels: bug

#456 Add test:update script to 1.x ui-tests
  ui-tests/package.json
Labels: bug

#454 [1.x] Fix "event loop is already running" bug on Linux
  jupyter_scheduler/scheduler.py
  ui-tests/tests/jupyter_scheduler.spec.ts-snapshots/list-view-linux.png
Labels: bug

#457 Telemetry patch
  src/index.tsx
  src/notebook-jobs-panel.tsx
  src/tokens.ts
Labels: enhancement

#459 Removed onMouseDown handler to avoid double submission
  src/components/confirm-buttons.tsx
Labels: bug
