Repository jupyter-server/jupyter-scheduler, pull requests merged in 2024-04, with the labels that each got.

#502 Update Release Scripts
  .github/workflows/prep-release.yml
  .github/workflows/publish-changelog.yml
  .github/workflows/publish-release.yml
  RELEASE.md
Labels: maintenance

#507 [1.2.x] Ignore check-wheel-contents W002 duplciate files error, add pydantic_v1 module, add pytest-cov dependency
  .pre-commit-config.yaml
  jupyter_scheduler/__init__.py
  jupyter_scheduler/handlers.py
  jupyter_scheduler/models.py
  jupyter_scheduler/pydantic_v1/__init__.py
  jupyter_scheduler/pydantic_v1/dataclasses.py
  jupyter_scheduler/pydantic_v1/main.py
  jupyter_scheduler/task_runner.py
  jupyter_scheduler/tests/test_handlers.py
  pyproject.toml
  ui-tests/jupyter_server_test_config.py
Labels: bug

#508 Clarify support lifecycle after JupyterLab 3 end of maintenance
  README.md
  docs/conf.py
  docs/users/index.md
Labels: documentation, maintenance

#510 Package input files (no autodownload, no multiprocessing DownloadManager)
  docs/operators/index.md
  docs/users/images/create_job_form.png
  docs/users/index.md
  jupyter_scheduler/executors.py
  jupyter_scheduler/job_files_manager.py
  jupyter_scheduler/models.py
  jupyter_scheduler/orm.py
  jupyter_scheduler/scheduler.py
  jupyter_scheduler/tests/test_execution_manager.py
  jupyter_scheduler/tests/test_job_files_manager.py
  jupyter_scheduler/tests/test_scheduler.py
  jupyter_scheduler/tests/test_staging_dir/job-3/output_side_effect.txt
  jupyter_scheduler/tests/test_staging_dir/job-3/side_effects.ipynb
  jupyter_scheduler/utils.py
  src/components/files-directory-link.tsx
  src/components/input-folder-checkbox.tsx
  src/components/job-file-link.tsx
  src/components/job-row.tsx
  src/handler.ts
  src/mainviews/create-job.tsx
  src/mainviews/detail-view/job-definition.tsx
  src/mainviews/detail-view/job-detail.tsx
  src/model.ts
  ui-tests/tests/jupyter_scheduler.spec.ts-snapshots/create-view-from-filebrowser-linux.png
  ui-tests/tests/jupyter_scheduler.spec.ts-snapshots/create-view-from-toolbar-linux.png
Labels: enhancement

#512 [1.x] Package input files (no autodownload, no multiprocessing DownloadManager) (#510)
  docs/operators/index.md
  docs/users/images/create_job_form.png
  docs/users/index.md
  jupyter_scheduler/executors.py
  jupyter_scheduler/job_files_manager.py
  jupyter_scheduler/models.py
  jupyter_scheduler/orm.py
  jupyter_scheduler/scheduler.py
  jupyter_scheduler/tests/test_execution_manager.py
  jupyter_scheduler/tests/test_job_files_manager.py
  jupyter_scheduler/tests/test_scheduler.py
  jupyter_scheduler/tests/test_staging_dir/job-3/output_side_effect.txt
  jupyter_scheduler/tests/test_staging_dir/job-3/side_effects.ipynb
  jupyter_scheduler/utils.py
  src/components/files-directory-link.tsx
  src/components/input-folder-checkbox.tsx
  src/components/job-file-link.tsx
  src/components/job-row.tsx
  src/handler.ts
  src/mainviews/create-job.tsx
  src/mainviews/detail-view/job-definition.tsx
  src/mainviews/detail-view/job-detail.tsx
  src/model.ts
  ui-tests/tests/jupyter_scheduler.spec.ts-snapshots/create-view-from-filebrowser-linux.png
  ui-tests/tests/jupyter_scheduler.spec.ts-snapshots/create-view-from-toolbar-linux.png
Labels: enhancement

#513 Add tests for Scheduler job and job definition creation with input folder, refactor execution manager test
  conftest.py
  jupyter_scheduler/tests/test_execution_manager.py
  jupyter_scheduler/tests/test_root_dir/job-5/a/b/helloworld.txt
  jupyter_scheduler/tests/test_root_dir/job-5/import-helloworld.ipynb
  jupyter_scheduler/tests/test_scheduler.py
  jupyter_scheduler/tests/test_staging_dir/job-4/output_side_effect.txt
  jupyter_scheduler/tests/test_staging_dir/job-4/side_effects.ipynb
Labels: enhancement, Testing

#515 [1.x] Add tests for Scheduler job and job definition creation with input folder, refactor execution manager test (#513)
  conftest.py
  jupyter_scheduler/tests/test_execution_manager.py
  jupyter_scheduler/tests/test_root_dir/job-5/a/b/helloworld.txt
  jupyter_scheduler/tests/test_root_dir/job-5/import-helloworld.ipynb
  jupyter_scheduler/tests/test_scheduler.py
  jupyter_scheduler/tests/test_staging_dir/job-4/output_side_effect.txt
  jupyter_scheduler/tests/test_staging_dir/job-4/side_effects.ipynb
Labels: enhancement, Testing
